# Generated by Django 2.1.7 on 2019-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('edition', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('file', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_bookdata',
            },
        ),
    ]
