# Generated by Django 2.1.7 on 2019-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
