# Generated by Django 2.2 on 2019-04-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190402_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='summarydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('summary_id', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=2000)),
                ('date', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('chapter', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_summarydata',
            },
        ),
    ]
