# Generated by Django 2.2 on 2019-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_summarydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarydata',
            name='summary',
            field=models.CharField(max_length=4000),
        ),
    ]
