# Generated by Django 2.2 on 2019-04-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190418_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='flasdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_id', models.CharField(max_length=30)),
                ('flash', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_flasdata',
            },
        ),
    ]
