# Generated by Django 2.2 on 2019-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_flasdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flasdata',
            name='flash',
            field=models.CharField(max_length=2000),
        ),
    ]
