# Generated by Django 2.2 on 2019-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190425_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='flasdata',
            name='chapter',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
