# Generated by Django 2.2 on 2019-04-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20190428_1411'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
