# Generated by Django 2.2 on 2019-04-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20190428_1412'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='tbl_login',
        ),
    ]
