# Generated by Django 2.2 on 2019-04-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20190428_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
