# Generated by Django 2.2 on 2019-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20190428_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='user',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
