# Generated by Django 2.2 on 2019-05-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_bookdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='questiondata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userdid', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=30)),
                ('chapter', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_question',
            },
        ),
    ]
