# Generated by Django 2.2 on 2019-05-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_questiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondata',
            old_name='userdid',
            new_name='userid',
        ),
    ]
